/* Toggle stuff: mobile VS tablet, desktop */

// Globals
var introLeadIn = document.querySelector('.intro-lead-in');
var introHeading = document.querySelector('.intro-heading');
var faqPara = document.querySelectorAll('#faq p');
var faqShowHideSpan = document.querySelectorAll('#faq span.show-hide-text');
var fontAwesomePlus = document.querySelectorAll('a i.fa-plus');
var fontAwesomeMinus = document.querySelectorAll('a i.fa-minus');

// INJECTED TEXT
var faqParaText = [
   "A symptom checker is a system allowing the detection of any subjective evidence of an ailment or medical condition. Subjective evidence is defined as a symptom, as only patients can discover them. The symptom checker may be run by the user/patient or with the assistance of medical personnel, as symptoms are, by definition, known to the patient only. In opposition, a sign is objectively determined by a medical professional. For example, blood coming out of the nose is a sign. It is apparent to the patient, physician, and others. Dizziness, low back pain, tingling in the feet or anxiety are all symptoms, as only the user/patient can perceive them. A symptom checker can be of different forms. The most frequent ones are either keyword based or artificial intelligence based. All symptom checkers will try to determine a differential diagnosis (DDX). We consider MEDoctor's symptom checker to be of a superior type, as it is patented, with its patents granted (see US Patent #7,149,756 A - December, 2006 - ,and EPO Patent #EP 1284639 B1 - July, 2008.",
   "Our mission is to empower you to help yourself determine your health problems. The MEDoctor Symptom Checker won't replace a medical visit to your doctor to have the final diagnosis and the correct treatment, but will be useful to identify which pain, disease or illness can correspond to the symptoms you have. The MEDoctor Symptom Checker is a guide that will help you for all kinds of problems, for a benign disease as a cold or something more serious as a cancer. MEDoctor is indeed one of the world's most advanced symptom checkers. And it is the only patented symptom checker on the Web.",
   "You the individual are the answer to the challenges of health care. The right to protect the health and well-being of every person, of those we love, is a basic human right. Health care costs are the number 1 leading cause for personal bankruptcy in the USA today. 40% to 60% of patients are not compliant for a diagnosis, because they can't afford the bill, because they have a high deductible. Today the patient receives no copies of their diagnosis process '... because it could be dangerous...'. And they cannot see a physician without prior approval by their insurance.",
   "We see a world where every person knows what potential disease he or she might have prior to seeing a clinician and thereby make the affordable choices for their health. We want to give you access to actionable health information at the time and frequency it matters. Every person needs to understand the risks of their condition before they undergo any costs. Patient engagement comes with knowledge. And knowledge comes with access to information. We are redefining the paradigm of diagnosis. All information becomes accessible before seeing the clinician, at any place, any time, any frequency. Technology is transforming the world. With that, we will begin to change our health care system and our lives. MEDoctor delivers 24/7, immediate, accurate health assessments for FREE and from any place a connection is available (Web, smart phone). This health assessment is generated by a sophisticated and patented algorithm. All information becomes accessible before seeing the clinician, at any place, at any frequency, at the time it matters. Early health recommendations are provided for your better choices.",
   "MEDoctor practices policies that are intended to protect the confidentiality of personal information obtained from users in the course of its regular business functions. We are committed to protecting information about users, especially the confidential nature of any personal information (PI) we collect. Personal information is information that is capable of being associated with an individual through one or more identifiers including but not limited to, a Social Security number, a driver's license number, a state identification card number, an account number, a credit or debit card number, a passport number, an alien registration number or a health insurance identification number, and does not include publicly available information that is lawfully made available to the general public from federal, state or local government records, or widely distributed media. To this end, the MEDoctor Symptom Checker does not require that you identify yourself in any way other than an account name and password that you yourself choose. While the name you choose may be associated with you or your activities on the Internet (such as an email address), there is no requirement that it be so. MEDoctor considers the account name, password, and entered data to be sensitive information and restricts access to it."
];

/* WINDOW ONLOAD and RESIZE */ //TODO
window.onload = (function () {
   toggleMobileDesktop();
  addListeners();
})();
window.onresize = toggleMobileDesktop;

/* ADD LISTENERS */
function addListeners() {
   // expand text listeners
   for (var i = 0; i < fontAwesomePlus.length; i++) {
      fontAwesomePlus[i].addEventListener('click', function (e) {
         e.preventDefault();
         toggleText('maximize', e);
      })
   }
   // shrink text listeners
   for (var i = 0; i < fontAwesomeMinus.length; i++) {
      fontAwesomeMinus[i].addEventListener('click', function (e) {
         e.preventDefault();
         toggleText('minimize', e);
      })
   }
}

/* TOGGLE MOBILE-DESKTOP */
function toggleMobileDesktop() {
   if (window.innerWidth < 768) {
      // header text
      introLeadIn.textContent = 'The Only Patented Artificial Intelligence Symptom Checker';
      introHeading.textContent = '';
     turnOnTextToggle(false); 
   } else {
      // header text
      introLeadIn.textContent = 'The Only Patented Artificial Intelligence Symptom Checker';
      introHeading.textContent = ''; // TODO
      turnOnTextToggle(true);
   }
}

/* TURN ON TEXT TOGGLE */
function turnOnTextToggle(bool) {
   if (bool) {
      showFAQSpan(true); 
      for (var i = 0; i < faqPara.length; i++) {
         // minimize text to 300
         faqPara[i].innerText = faqParaText[i].slice(0, 300) + '...';
      }
   } else {
      showFAQSpan(false); 
      for (i in faqPara) {
         faqPara[i].innerText = faqParaText[i];
      }
   }
}

/* SHOW FAQs SPAN */
function showFAQSpan(bool) {
   if (bool) {
      // unhide span, but hide both FA icons
      for (var i = 0; i < faqShowHideSpan.length; i++) {
         faqShowHideSpan[i].style.visibility = "";
         // hide minus FA icon
         fontAwesomeMinus[i].style.visibility = "hidden";
      }
   } else {
      for (var i = 0; i < faqShowHideSpan.length; i++) {
         faqShowHideSpan[i].style.visibility = "hidden";
      }
   }
}

/* TOGGLE TEXT */
function toggleText(type, event) {
   var iNum = event.target.getAttribute('data-i-num');
   if (type === 'minimize') {
      // hide minus and show plus FA icons
      fontAwesomeMinus[iNum].style.visibility = "hidden";
      fontAwesomePlus[iNum].style.visibility = "";
   } else if (type === 'maximize') {
      // hide plus and show minus FA icons
      fontAwesomePlus[iNum].style.visibility = "hidden";
      fontAwesomeMinus[iNum].style.visibility = "";
   }
}